# modules/magscot.smk
# MAGScoT bin scoring/refinement module

rule magscot_generate_markers:
    """
    Generate MAGScoT marker mapping TSV (gene_id, marker, e-value) from MAG FASTAs.
    This runs prodigal + hmmscan inside magscot.sif and converts hits to 3-column format.
    """
    input:
        metabat2=f"{OUTPUT_DIR}/{{sample}}/binning/metabat2_bins",
        maxbin2=f"{OUTPUT_DIR}/{{sample}}/binning/maxbin2_bins",
        concoct=f"{OUTPUT_DIR}/{{sample}}/binning/concoct_bins"
    output:
        hmm=f"{OUTPUT_DIR}/{{sample}}/bin_refinement/magscot/{{sample}}.markers.tsv",
        done=f"{OUTPUT_DIR}/{{sample}}/bin_refinement/magscot/markers.done"
    params:
        outdir=f"{OUTPUT_DIR}/{{sample}}/bin_refinement/magscot",
        container="containers/magscot.sif",
        marker_hmm_db=lambda wildcards: config.get("magscot", {}).get("marker_hmm_db", ""),
        hmmer_evalue=lambda wildcards: str(config.get("magscot", {}).get("hmmer_evalue", 1e-10))
    threads: config["threads"]
    log: "logs/magscot_markers_{sample}.log"
    shell:
        """
        mkdir -p {params.outdir} logs
        : > {log}

        if [ -z "{params.marker_hmm_db}" ]; then
            echo "config.magscot.marker_hmm_db is required for marker generation." >> {log}
            exit 1
        fi
        if [ ! -f "{params.marker_hmm_db}" ]; then
            echo "MAGScoT marker HMM DB not found: {params.marker_hmm_db}" >> {log}
            exit 1
        fi

        tmpdir="{params.outdir}/work_markers"
        rm -rf "$tmpdir"
        mkdir -p "$tmpdir"
        hits_raw="$tmpdir/hits.raw.tsv"
        : > "$hits_raw"

        for f in {input.metabat2}/*.fa {input.maxbin2}/*.fa {input.concoct}/*.fa; do
            [ -e "$f" ] || continue
            prefix=$(basename "$f" .fa)
            faa="$tmpdir/${{prefix}}.faa"
            tbl="$tmpdir/${{prefix}}.tblout"

            singularity exec {params.container} prodigal -i "$f" -a "$faa" -p meta -q >> {log} 2>&1
            if [ ! -s "$faa" ]; then
                continue
            fi

            singularity exec {params.container} hmmscan \
                --noali \
                --cpu {threads} \
                -E {params.hmmer_evalue} \
                --tblout "$tbl" \
                "{params.marker_hmm_db}" "$faa" >> {log} 2>&1

            awk 'BEGIN{{OFS="\t"}} !/^#/ {{print $3, $1, $5}}' "$tbl" >> "$hits_raw"
        done

        if [ ! -s "$hits_raw" ]; then
            echo "No marker hits were generated by hmmscan." >> {log}
            exit 1
        fi

        # Keep best (lowest e-value) hit per gene_id + marker pair.
        sort -k1,1 -k2,2 -k3,3g "$hits_raw" | awk 'BEGIN{{OFS="\t"}} !seen[$1"\t"$2]++ {{print $1, $2, $3}}' > {output.hmm}
        touch {output.done}
        """

rule magscot_refine_bins:
    """
    Run MAGScoT using bin/contig/set input assembled from metabat2, maxbin2, and concoct bins.
    The marker mapping (--hmm) file must be provided in config.magscot.hmm.
    """
    input:
        metabat2=f"{OUTPUT_DIR}/{{sample}}/binning/metabat2_bins",
        maxbin2=f"{OUTPUT_DIR}/{{sample}}/binning/maxbin2_bins",
        concoct=f"{OUTPUT_DIR}/{{sample}}/binning/concoct_bins",
        hmm=f"{OUTPUT_DIR}/{{sample}}/bin_refinement/magscot/{{sample}}.markers.tsv",
        markers_done=f"{OUTPUT_DIR}/{{sample}}/bin_refinement/magscot/markers.done"
    output:
        table=f"{OUTPUT_DIR}/{{sample}}/bin_refinement/magscot/{{sample}}.input.tsv",
        done=f"{OUTPUT_DIR}/{{sample}}/bin_refinement/magscot/magscot.done"
    params:
        outdir=f"{OUTPUT_DIR}/{{sample}}/bin_refinement/magscot",
        container="containers/magscot.sif",
        out_base=lambda wildcards: f"{OUTPUT_DIR}/{wildcards.sample}/bin_refinement/magscot/" + config.get("magscot", {}).get("out", "MAGScoT"),
        profile=lambda wildcards: config.get("magscot", {}).get("profile", "bac120+ar53"),
        bin_separator=lambda wildcards: config.get("magscot", {}).get("bin_separator", "cleanbin"),
        score_a=lambda wildcards: str(config.get("magscot", {}).get("score_a", 1)),
        score_b=lambda wildcards: str(config.get("magscot", {}).get("score_b", 0.5)),
        score_c=lambda wildcards: str(config.get("magscot", {}).get("score_c", 0.5)),
        max_cont=lambda wildcards: str(config.get("magscot", {}).get("max_cont", 1)),
        threshold=lambda wildcards: str(config.get("magscot", {}).get("threshold", 0.5)),
        min_markers=lambda wildcards: str(config.get("magscot", {}).get("min_markers", 25)),
        min_sharing=lambda wildcards: str(config.get("magscot", {}).get("min_sharing", 0.8)),
        n_iterations=lambda wildcards: str(config.get("magscot", {}).get("n_iterations", 2)),
        score_only=lambda wildcards: bool(config.get("magscot", {}).get("score_only", False)),
        skip_merge_bins=lambda wildcards: bool(config.get("magscot", {}).get("skip_merge_bins", False))
    threads: config["threads"]
    log: "logs/magscot_{sample}.log"
    shell:
        """
        mkdir -p {params.outdir} logs
        : > {log}

        if [ ! -f "{input.hmm}" ]; then
            echo "MAGScoT marker mapping file not found: {input.hmm}" >> {log}
            exit 1
        fi

        # Build required MAGScoT input table: bin<TAB>contig<TAB>set (no header).
        : > {output.table}
        for f in {input.metabat2}/*.fa; do
            [ -e "$f" ] || continue
            b=$(basename "$f" .fa)
            awk -v bin="$b" -v set="metabat2" '/^>/{{c=substr($0,2); sub(/[ \t].*$/, "", c); print bin "\t" c "\t" set}}' "$f" >> {output.table}
        done
        for f in {input.maxbin2}/*.fa; do
            [ -e "$f" ] || continue
            b=$(basename "$f" .fa)
            awk -v bin="$b" -v set="maxbin2" '/^>/{{c=substr($0,2); sub(/[ \t].*$/, "", c); print bin "\t" c "\t" set}}' "$f" >> {output.table}
        done
        for f in {input.concoct}/*.fa; do
            [ -e "$f" ] || continue
            b=$(basename "$f" .fa)
            awk -v bin="$b" -v set="concoct" '/^>/{{c=substr($0,2); sub(/[ \t].*$/, "", c); print bin "\t" c "\t" set}}' "$f" >> {output.table}
        done

        if [ ! -s {output.table} ]; then
            echo "Generated MAGScoT input table is empty: {output.table}" >> {log}
            exit 1
        fi

        score_only_flag=""
        skip_merge_flag=""
        if [ "{params.score_only}" = "True" ]; then
            score_only_flag="--score_only"
        fi
        if [ "{params.skip_merge_bins}" = "True" ]; then
            skip_merge_flag="--skip_merge_bins"
        fi

        singularity exec {params.container} MAGScoT.R \
            -i {output.table} \
            --hmm {input.hmm} \
            -p {params.profile} \
            -o {params.out_base} \
            --bin_separator {params.bin_separator} \
            -a {params.score_a} \
            -b {params.score_b} \
            -c {params.score_c} \
            --max_cont {params.max_cont} \
            -t {params.threshold} \
            -m {params.min_markers} \
            -s {params.min_sharing} \
            -n {params.n_iterations} \
            $score_only_flag \
            $skip_merge_flag >> {log} 2>&1

        touch {output.done}
        """
